# Generated by Django 5.0.1 on 2024-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('cards', '0006_alter_card_choice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choise_cards', models.ManyToManyField(blank=True, default=None, to='cards.card', verbose_name='choise cards')),
            ],
        ),
        migrations.AddField(
            model_name='partition',
            name='choise_section',
            field=models.ManyToManyField(blank=True, default=None, to='boxes.section', verbose_name='choise section'),
        ),
    ]
