# Generated by Django 5.0.1 on 2024-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_section_partition_choise_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='srart_time',
            field=models.DateField(blank=True, null=True, verbose_name='srart time'),
        ),
    ]
