# Generated by Django 5.0.1 on 2024-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_box_srart_time'),
        ('cards', '0006_alter_card_choice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='card_box',
            field=models.ManyToManyField(blank=True, default=None, to='cards.card', verbose_name='card box'),
        ),
    ]
