# Generated by Django 5.0.1 on 2024-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_box_card_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='srart_time',
        ),
        migrations.AddField(
            model_name='box',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
