# Generated by Django 5.0.1 on 2024-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_remove_box_srart_time_box_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='learn_days',
            field=models.FloatField(blank=True, null=True, verbose_name='learn_days'),
        ),
    ]
