# Generated by Django 5.0.1 on 2024-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_box_learn_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='learn_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='learn_days'),
        ),
    ]
