# Generated by Django 5.0.1 on 2024-01-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='category',
            new_name='choice_category',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='choice_user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
