# Generated by Django 5.0.1 on 2024-01-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_category_card_choice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='choice_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.category', verbose_name='choice_category'),
        ),
    ]
