# Generated by Django 5.0.1 on 2024-01-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_choice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='choice_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.category', verbose_name='choice_category'),
        ),
    ]
